pipeline {
    agent any
    stages {
// -------------------------------------------------------------------------        
		stage('BR14') {
			steps {
				script{
					node( 'mainframe' ) {
					    echo 'execute BR14'
					    sh "/var/dbb/bin/groovyz /u/teccfd/br14.groovy"  
					    
 					}
				}
		     }
    	}
// -------------------------------------------------------------------------
		stage('Iebcopy') {
			steps {
				script{
					node( 'mainframe' ) {
					    echo 'execute Iebcopy'
					    sh "/var/dbb/bin/groovyz /u/teccfd/iebcopy.groovy" 
 					}
				}
		     }
    	}
// -------------------------------------------------------------------------

	}
}
